### ISSUE TITLE
invalid node type at position 1672

### ISSUE THREAD

**Issue by JSilva6** [tree-sitter/tree-sitter-typescript#221] opened 2022-09-01 02:29 UTC
After the latest sync on packer, treesitter have problems whenever it tries to enable typescript

```
Erro detectado ao processar BufReadPost Autocommands for "*":
Error executing lua callback: vim/filetype.lua:0: Vim(append):Error executing lua callback: .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:1
72: query: invalid node type at position 1672
stack traceback:
        [C]: in function '_ts_parse_query'
        .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:159: in function 'start'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:165: in function 'attach'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:477: in function 'attach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:500: in function 'reattach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:108: in function <...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:107>
        [C]: in function 'nvim_buf_set_option'
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        ...al/Cellar/neovim/0.7.2_1/share/nvim/runtime/filetype.lua:15: in function <...al/Cellar/neovim/0.7.2_1/share/nvim/runtime/filetype.lua:14>
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        ...al/Cellar/neovim/0.7.2_1/share/nvim/runtime/filetype.lua:15: in function <...al/Cellar/neovim/0.7.2_1/share/nvim/runtime/filetype.lua:14>
Erro detectado ao processar FileType Autocommands for "*":
Error executing lua callback: .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1672
stack traceback:
        [C]: in function '_ts_parse_query'
        .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:159: in function 'start'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:165: in function 'attach'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:477: in function 'attach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:500: in function 'reattach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:108: in function <...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:107
```

Neovim version: 0.7.2
Node version: 16.15.1
NPM version: 8.18.0

**Comment by hendrikvanantwerpen** [comment] 2022-09-01 10:02
Duplicate of #220.

**Closed by hendrikvanantwerpen** 2022-09-01 10:02 UTC
Labels: bug
