### ISSUE TITLE
Conditional ternary operator is not highlighted properly

### ISSUE THREAD

**Issue by carlosala** [tree-sitter/tree-sitter-typescript#200] opened 2021-12-15 22:28 UTC
The following piece of code is parsed properly but the highlight of the `?` is not correct, should be red instead of white.
The same exact code in javascript is highlighted properly.
![Screenshot from 2021-12-15 23-25-26](https://user-images.githubusercontent.com/66907184/146274661-834bfdcd-0441-48a1-a409-c8312820b15e.png)

**Comment by resolritter** [comment] 2022-01-08 05:48
Should be transferred to https://github.com/tree-sitter/tree-sitter-javascript since that is where the "?" ternary expression token is defined

https://github.com/tree-sitter/tree-sitter-javascript/blob/fdeb68ac8d2bd5a78b943528bb68ceda3aade2eb/grammar.js#L792

**Comment by carlosala** [comment] 2022-01-08 17:16
I don't think so, as javascript highlights properly this example. Should be easy to fix.

**Comment by Wilfred** [comment] 2022-01-12 04:43
This issue is affecting my project too. The code `true ? 1 : 2;` is parsed as:

```
{Node program (0, 0) - (1, 0)}
  {Node expression_statement (0, 0) - (0, 13)}
    {Node ternary_expression (0, 0) - (0, 12)}
      {Node true (0, 0) - (0, 4)} "true"
      {Node ? (0, 7) - (0, 7)} ""
      {Node number (0, 7) - (0, 8)} "1"
      {Node : (0, 9) - (0, 10)} ":"
      {Node number (0, 11) - (0, 12)} "2"
    {Node ; (0, 12) - (0, 13)} ";"
```

Note that the position of the `?` token is empty.

**Comment by Wilfred** [comment] 2022-01-12 04:49
Interestingly the `ternary_expression` rule is inherited from the javascript grammar, but it doesn't have this problem. `true ? 1 : 2;` is parsed in JS as:

```
{Node program (0, 0) - (1, 0)}
  {Node expression_statement (0, 0) - (0, 13)}
    {Node ternary_expression (0, 0) - (0, 12)}
      {Node true (0, 0) - (0, 4)} "true"
      {Node ? (0, 5) - (0, 6)} "?"
      {Node number (0, 7) - (0, 8)} "1"
      {Node : (0, 9) - (0, 10)} ":"
      {Node number (0, 11) - (0, 12)} "2"
    {Node ; (0, 12) - (0, 13)} ";"
```

**Comment by Wilfred** [comment] 2022-01-12 04:55
Given that the grammar rule in the typescript parser reuses the JS rule, I'm guessing it's an issue in `scanner.h`.

**Comment by Wilfred** [comment] 2022-01-12 05:29
Removing this loop seems to fix it:

https://github.com/tree-sitter/tree-sitter-typescript/blob/master/common/scanner.h#L175-L180

**Comment by Wilfred** [comment] 2022-01-12 05:37
Unfortunately the `?` is an anonymous token `_ternary_qmark`, and the tests don't seem to include any way to verify positions of any token.

**Comment by carlosala** [comment] 2022-01-12 09:56
The main issue with this is that `?` in javascript is only used for ternary operator, whether in typescript is also used for optional arguments in interfaces, etc.

**Comment by cmdcolin** [comment] 2022-06-28 15:09
not sure if related to this issue but I found something sort of similar with


```
export function foo() {
  return {
    ...(1 > 0
      ? {
          onClick: () => alert('hello'),
        }
      : {}),

    label: 'hello',
    onClick: () => alert('hello'),
  }
}
```

![Screenshot from 2022-06-28 09-06-17](https://user-images.githubusercontent.com/6511937/176214118-5bdbb05d-a5a4-4023-99c3-4189c66c67b6.png)

With `1>0` it looks ok to me, but replacing `1>0` with `true` makes the highlighting go away. This appears specific to .ts file type, .js seems ok

![Screenshot from 2022-06-28 09-06-35](https://user-images.githubusercontent.com/6511937/176214194-9150d521-106f-42bc-92f8-3de47ee8b954.png)

**Comment by tom95** [comment] 2022-07-03 07:39
Hi @cmdcolin, I was not able to reproduce the error, potentially because I have a different highlights configuration than you?

If possible, you could try and run tree-sitter with this potential fix for this issue https://github.com/tree-sitter/tree-sitter-typescript/pull/215 and see if it does indeed also fix the issue you reported.

**Comment by carlosala** [comment] 2022-07-03 10:19
I'll check that later today or tomorrow, we should push it because it's really shitty to not have proper highlighting

**Comment by cmdcolin** [comment] 2022-07-03 17:02
@tom95 I think it is reproducible on a pretty stripped down config. i tried with neovim nightly (0.8 branch) and 0.7.2  and it's the same

how would i test out the branch?

**Comment by tom95** [comment] 2022-07-04 05:49
@cmdcolin looking at neovim docs, I believe you should be following these steps to add a custom version of typescript highlighting: https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers

As URL, you should specify `https://github.com/tom95/tree-sitter-typescript` and as branch `ternary-range-200`.

**Comment by cmdcolin** [comment] 2022-07-05 19:05
I actually ran ":TSInstall typescript" and it fixed my issue (presumably this updated the typescript tree-sitter module) so my pre-mentioned issue with the codesnippet is probably unrelated to this issue possibly....will hide comments

**Closed** 2022-07-06 19:52 UTC
Labels: bug
